import { UIProduct, UIProductVariant, UIOrder, UIVoucher, UIUser } from "./ui-types"

export const mockProducts: UIProduct[] = [
  {
    id: 'prod-1',
    name: 'KM ITB Premium Hoodie',
    slug: 'km-itb-premium-hoodie',
    description: 'Premium quality hoodie featuring the official KM ITB logo. Perfect for campus life and beyond. Made from 100% cotton blend for maximum comfort and durability.',
    price: 299000,
    images: ['/images/product-1.jpg', '/images/product-1-alt.jpg'],
    category: 'APPAREL',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-05-01'),
    
  },
  {
    id: 'prod-2',
    name: 'KM ITB Classic T-Shirt',
    slug: 'km-itb-classic-tshirt',
    description: 'Classic crew neck t-shirt with minimalist KM ITB design. Comfortable, breathable, and versatile for everyday wear.',
    price: 129000,
    images: ['/images/product-2.jpg', '/images/product-2-alt.jpg'],
    category: 'APPAREL',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-05-01'),
    
  },
  {
    id: 'prod-3',
    name: 'KM ITB Baseball Cap',
    slug: 'km-itb-baseball-cap',
    description: 'Adjustable baseball cap with embroidered KM ITB logo. Perfect for sunny days and casual outings.',
    price: 89000,
    images: ['/images/product-3.jpg', '/images/product-3-alt.jpg'],
    category: 'ACCESSORIES',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-05-01'),
    
  },
  {
    id: 'prod-4',
    name: 'Jaket Varsity KM ITB',
    slug: 'jaket-varsity-km-itb',
    description: 'Premium varsity jacket with KM ITB embroidered patches. Perfect for campus events and celebrations. Features contrast sleeves and classic silhouette.',
    price: 499000,
    images: ['/images/product-4.jpg', '/images/product-4-alt.jpg'],
    category: 'APPAREL',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-05-01'),
    
  },
  {
    id: 'prod-5',
    name: 'Totebag KM ITB',
    slug: 'totebag-km-itb',
    description: 'Spacious canvas totebag with KM ITB logo print. Ideal for books, laptops, or daily essentials. Durable handles and high-quality canvas material.',
    price: 179000,
    images: ['/images/product-5.jpg', '/images/product-5-alt.jpg'],
    category: 'ACCESSORIES',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-05-01'),
    
  },
  {
    id: 'prod-6',
    name: 'Lanyard ITB',
    slug: 'lanyard-itb',
    description: 'Practical nylon lanyard with ITB university logo. Perfect for ID cards, keys, or badges. Adjustable length with detachable clip.',
    price: 49000,
    images: ['/images/product-6.jpg', '/images/product-6-alt.jpg'],
    category: 'ACCESSORIES',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-05-01'),
    
  },
  {
    id: 'prod-7',
    name: 'Sticker Pack Official',
    slug: 'sticker-pack-official',
    description: 'Set of 5 vinyl stickers featuring KM ITB designs. Weather-resistant and perfect for laptops, water bottles, and skateboards. Vibrant colors on glossy finish.',
    price: 29000,
    images: ['/images/product-7.jpg', '/images/product-7-alt.jpg'],
    category: 'MERCHANDISE',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-05-01'),
    
  },
  {
    id: 'prod-8',
    name: 'Notebook Official Merch',
    slug: 'notebook-official-merch',
    description: 'Premium A5 notebook with KM ITB branding. 100 pages of quality paper for note-taking, sketching, or journaling. Perfect for students and professionals.',
    price: 69000,
    images: ['/images/product-8.jpg', '/images/product-8-alt.jpg'],
    category: 'MERCHANDISE',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-05-01'),
    
  },
]

export const mockVariants: UIProductVariant[] = [
  // Hoodie variants
  {
    id: 'var-1',
    productId: 'prod-1',
    name: 'Black - M',
    color: 'Black',
    size: 'M',
    sku: 'HOODIE-BLK-M',
    stock: 45,
  },
  {
    id: 'var-2',
    productId: 'prod-1',
    name: 'Black - L',
    color: 'Black',
    size: 'L',
    sku: 'HOODIE-BLK-L',
    stock: 32,
  },
  {
    id: 'var-3',
    productId: 'prod-1',
    name: 'Navy - M',
    color: 'Navy',
    size: 'M',
    sku: 'HOODIE-NVY-M',
    stock: 28,
  },
  // T-Shirt variants
  {
    id: 'var-4',
    productId: 'prod-2',
    name: 'White - M',
    color: 'White',
    size: 'M',
    sku: 'TSHIRT-WHT-M',
    stock: 120,
  },
  {
    id: 'var-5',
    productId: 'prod-2',
    name: 'White - L',
    color: 'White',
    size: 'L',
    sku: 'TSHIRT-WHT-L',
    stock: 95,
  },
  {
    id: 'var-6',
    productId: 'prod-2',
    name: 'Black - M',
    color: 'Black',
    size: 'M',
    sku: 'TSHIRT-BLK-M',
    stock: 87,
  },
  // Cap variants
  {
    id: 'var-7',
    productId: 'prod-3',
    name: 'Black',
    color: 'Black',
    size: 'One Size',
    sku: 'CAP-BLK-OS',
    stock: 200,
  },
  {
    id: 'var-8',
    productId: 'prod-3',
    name: 'White',
    color: 'White',
    size: 'One Size',
    sku: 'CAP-WHT-OS',
    stock: 165,
  },
  // Varsity jacket variants
  {
    id: 'var-9',
    productId: 'prod-4',
    name: 'Black - S',
    color: 'Black',
    size: 'S',
    sku: 'VARSITY-BLK-S',
    stock: 25,
  },
  {
    id: 'var-10',
    productId: 'prod-4',
    name: 'Black - M',
    color: 'Black',
    size: 'M',
    sku: 'VARSITY-BLK-M',
    stock: 38,
  },
  {
    id: 'var-11',
    productId: 'prod-4',
    name: 'Black - L',
    color: 'Black',
    size: 'L',
    sku: 'VARSITY-BLK-L',
    stock: 22,
  },
  // Totebag variants
  {
    id: 'var-12',
    productId: 'prod-5',
    name: 'Natural Canvas',
    color: 'Natural',
    size: 'One Size',
    sku: 'TOTE-NAT-OS',
    stock: 145,
  },
  {
    id: 'var-13',
    productId: 'prod-5',
    name: 'Black Canvas',
    color: 'Black',
    size: 'One Size',
    sku: 'TOTE-BLK-OS',
    stock: 98,
  },
  // Lanyard variants
  {
    id: 'var-14',
    productId: 'prod-6',
    name: 'Black',
    color: 'Black',
    size: 'One Size',
    sku: 'LANYARD-BLK-OS',
    stock: 350,
  },
  {
    id: 'var-15',
    productId: 'prod-6',
    name: 'Navy',
    color: 'Navy',
    size: 'One Size',
    sku: 'LANYARD-NVY-OS',
    stock: 280,
  },
  // Sticker pack variants
  {
    id: 'var-16',
    productId: 'prod-7',
    name: 'Standard Set',
    color: 'Mixed',
    size: 'One Size',
    sku: 'STICKER-STD-OS',
    stock: 500,
  },
  // Notebook variants
  {
    id: 'var-17',
    productId: 'prod-8',
    name: 'White Cover',
    color: 'White',
    size: 'A5',
    sku: 'NOTE-WHT-A5',
    stock: 180,
  },
  {
    id: 'var-18',
    productId: 'prod-8',
    name: 'Black Cover',
    color: 'Black',
    size: 'A5',
    sku: 'NOTE-BLK-A5',
    stock: 156,
  },
]

export const mockVouchers: UIVoucher[] = [
  {
    id: 'vouch-1',
    code: 'WELCOME10',
    description: '10% discount for new customers',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    maxUsage: 100,
    usageCount: 0,
    minPurchaseAmount: 100000,
    expiresAt: new Date('2024-12-31'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'vouch-2',
    code: 'SAVE50K',
    description: 'Flat 50,000 IDR off',
    discountType: 'FIXED',
    discountValue: 50000,
    maxUsage: 50,
    usageCount: 0,
    minPurchaseAmount: 200000,
    expiresAt: new Date('2024-12-31'),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockUsers: UIUser[] = [
  {
    id: 'user-1',
    email: 'budi@example.com',
    name: 'Budi Santoso',
    phone: '08123456789',
    role: 'BUYER',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-05-01'),
      },
  {
    id: 'user-2',
    email: 'admin@km-itb.com',
    name: 'Admin KM ITB',
    phone: '08198765432',
    role: 'ADMIN',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-05-01'),
      },
]

export const mockOrders: UIOrder[] = [
  {
    id: 'order-1',
    orderNumber: 'KM-20240501-ABC123',
    userId: 'user-1',
    items: [
      {
        id: 'oi-1',
        orderId: 'order-1',
        productId: 'prod-1',
        variantId: 'var-1',
        quantity: 1,
        unitPrice: 299000,
        subtotal: 299000,
      },
    ],
    subtotal: 299000,
    taxAmount: 29900,
    shippingCost: 50000,
    discountAmount: 0,
    total: 378900,
    deliveryMethod: 'DELIVERY' as any, // TODO: Replace with proper enum in Phase 2
    status: 'PAYMENT_RECEIVED' as any, // TODO: Replace with proper enum in Phase 2
    paymentStatus: 'PAID' as any, // TODO: Replace with proper enum in Phase 2
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-05-02'),
  },
  {
    id: 'order-2',
    orderNumber: 'KM-20240502-DEF456',
    userId: 'user-1',
    items: [
      {
        id: 'oi-2',
        orderId: 'order-2',
        productId: 'prod-2',
        variantId: 'var-4',
        quantity: 2,
        unitPrice: 129000,
        subtotal: 258000,
      },
      {
        id: 'oi-3',
        orderId: 'order-2',
        productId: 'prod-3',
        variantId: 'var-7',
        quantity: 1,
        unitPrice: 89000,
        subtotal: 89000,
      },
    ],
    subtotal: 347000,
    taxAmount: 34700,
    shippingCost: 0,
    discountAmount: 0,
    total: 381700,
    deliveryMethod: 'PICKUP' as any, // TODO: Replace with proper enum in Phase 2
    status: 'WAITING_PAYMENT' as any, // TODO: Replace with proper enum in Phase 2
    paymentStatus: 'PENDING' as any, // TODO: Replace with proper enum in Phase 2
    createdAt: new Date('2024-05-02'),
    updatedAt: new Date('2024-05-02'),
  },
]
